openapi: 3.0.0
info:
  title: Carts
  version: 1.0.0
  description: Documentation of the Carts API using Swagger.

paths:
  /api/carts/{cId}:
    get:
      summary: Get a cart by ID
      description: Returns a specific cart based on the provided ID.
      tags:
        - Carts
      parameters:
        - name: cId
          in: path
          description: ID of the cart to retrieve.
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response. Returns the cart details.
        '404':
          description: Cart not found.

    put:
      summary: Clear products in cart
      description: Removes all products from the cart.
      tags:
        - Carts
      parameters:
        - name: cId
          in: path
          description: ID of the cart to clear products.
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Products cleared from the cart successfully.
        '404':
          description: Cart not found.

  /api/carts/{cId}/deleteproduct/{pId}:
    delete:
      summary: Remove only a quantity of the product in the cart.
      description: Lower the quantity of the same product.
      tags:
        - Carts
      parameters:
        - name: cId
          in: path
          description: ID of the cart.
          required: true
          schema:
            type: string
        - name: pId
          in: path
          description: ID of the product to delete.
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Product removed successfully.
        '404':
          description: Cart or Product not found.

  /api/carts/{cId}/purchase:
    get:
      summary: Purchase cart
      description: Simulates the purchase of the cart's products.
      tags:
        - Carts
      parameters:
        - name: cId
          in: path
          description: ID of the cart to purchase.
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response. Returns the purchase details.
        '404':
          description: Cart not found.

  /api/carts:
    post:
      summary: Create a new cart
      description: Creates a new cart.
      tags:
        - Carts
      responses:
        '201':
          description: Cart created successfully.

  /api/carts/{cId}/addproduct/{pId}:
    put:
      summary: Add product to cart
      description: Adds a product to the cart.
      tags:
        - Carts
      parameters:
        - name: cId
          in: path
          description: ID of the cart to update.
          required: true
          schema:
            type: string
        - name: pId
          in: path
          description: ID of the product to add to the cart.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  minimum: 1
                  description: The quantity of the product to add to the cart (default is 1).
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Product added to the cart successfully.
        '404':
          description: Cart or product not found.
        '409':
          description: Product already exists in the cart.

  /api/carts/{cId}/products/{pId}:
    delete:
      summary: Remove entire product from cart
      description: Removes a specific product from the cart.
      tags:
        - Carts
      parameters:
        - name: cId
          in: path
          description: ID of the cart to update.
          required: true
          schema:
            type: string
        - name: pId
          in: path
          description: ID of the product to remove from the cart.
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Product removed from the cart successfully.
        '404':
          description: Cart or product not found.
    